import { StyleSheet } from "react-native"
import { Colors } from "@/constants/Colors"

export const styles = StyleSheet.create({
  container: {
    width: "48%",
    aspectRatio: 0.85,
    marginBottom: 16,
    borderRadius: 20,
    elevation: 4,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.15,
    shadowRadius: 4,
  },
  gradient: {
    flex: 1,
    borderRadius: 20,
    padding: 16,
    alignItems: "center",
    justifyContent: "space-between",
    position: "relative",
    borderWidth: 1,
    borderColor: Colors.light.border + "40",
  },
  deleteButton: {
    position: "absolute",
    top: 10,
    right: 10,
    zIndex: 10,
  },
  deleteButtonGradient: {
    width: 22,
    height: 22,
    borderRadius: 11,
    justifyContent: "center",
    alignItems: "center",
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.22,
    shadowRadius: 2.22,
  },
  imageContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 16,
    marginBottom: 8,
  },
  imageWrapper: {
    position: "relative",
  },
  categoryImage: {
    width: 100,
    height: 100,
    borderRadius: 16,
    borderWidth: 2,
    borderColor: Colors.light.border + "60",
  },
  imageOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    borderRadius: 16,
    backgroundColor: "rgba(0,0,0,0.05)",
  },
  defaultIconContainer: {
    width: 55,
    height: 55,
    borderRadius: 16,
    justifyContent: "center",
    alignItems: "center",
  },
  iconBackground: {
    width: 55,
    height: 55,
    borderRadius: 16,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: Colors.light.primary + "30",
  },
  infoContainer: {
    alignItems: "center",
    flex: 1,
    justifyContent: "flex-end",
    width: "100%",
  },
  categoryName: {
    fontSize: 13,
    fontWeight: "700",
    color: Colors.light.text,
    textAlign: "center",
    marginBottom: 6,
    lineHeight: 16,
    letterSpacing: 0.2,
  },
  categoryDescription: {
    fontSize: 10,
    color: Colors.light.textSecondary,
    textAlign: "left",
    paddingLeft: 15,
    marginTop: 2,
    opacity: 0.8,
  },
  productCountContainer: {
    alignItems: "center",
    marginTop: 4,
  },
  productCountBadge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: Colors.light.primary + "15",
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 10,
    gap: 3,
  },
  productCount: {
    fontSize: 10,
    color: Colors.light.primary,
    fontWeight: "600",
  },
  editIndicator: {
    position: "absolute",
    bottom: 10,
    left: 10,
  },
  editIndicatorGradient: {
    width: 20,
    height: 20,
    borderRadius: 10,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: Colors.light.primary + "30",
  },
  statusIndicator: {
    position: "absolute",
    top: 10,
    left: 10,
  },
  statusDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: "white",
  },
})
