import { StyleSheet } from "react-native"

export const styles = StyleSheet.create({
  containerTransparent: {
    backgroundColor: "rgba(0, 0, 0, 0.8)",
    width: "100%",
    height: "100%",
    position: "absolute",
  },
  container: {
    width: "100%",
    backgroundColor: "white",
    margin: "auto",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "space-between",
    borderRadius: 10,
    paddingVertical: 20,
    paddingHorizontal: 15,
  },
  containerForm: {
    width: "100%",
    display: "flex",
    flexDirection: "column",
    margin: "auto",
    alignItems: "center",
  },
  containerStep1: {
    width: "90%",
    margin: "auto",
  },
  containerStep2: {
    width: "100%",
    backgroundColor: "#f8f9fa",
  },
  containerStep3: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  ContainerHeader: {
    position: "relative",
    width: "100%",
    alignSelf: "flex-start",
  },
  ContainerFooter: {
    width: "100%",
    alignSelf: "flex-end",
    marginTop: 20,
  },
  test: {
    width: "100%",
    display: "flex",
    flex: 1,
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 20,
  },
  spinner: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  warningContainer: {
    borderRadius: 12,
    padding: 16,
    marginBottom: 20,
    marginHorizontal: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  loadingContainer: {
    flex: 1,
    width: "90%",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 20,
    overflow: "hidden",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.2,
    shadowRadius: 16,
    elevation: 10,
  },
  loadingGradient: {
    width: "100%",
    padding: 32,
    alignItems: "center",
    justifyContent: "center",
    minHeight: 300,
  },
  lottieAnimation: {
    width: 220,
    height: 180,
    marginTop: 16,
  },
  plansScrollContainer: {
    paddingHorizontal: 20,
    paddingVertical: 10,
    gap: 16,
  },
})
