import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  MainContainer: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    marginVertical: 0,
    paddingHorizontal: 15,
  },
  containerCardMethodOfPay: {
    margin: 10,
    backgroundColor: "#1e1e2f",
    width: "100%",
    maxWidth: 350,
    borderRadius: 20,
    padding: 24,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 10,
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
  },
  WhiteText: {
    color: "white",
    fontSize: 14,
  },
  WhiteTextBold: {
    color: "white",
    fontWeight: "700",
    fontSize: 18,
    marginBottom: 8,
  },
  WhiteTextPrice: {
    color: "#20c997",
    fontWeight: "700",
    fontSize: 22,
    marginRight: 4,
  },
  ContainerRow: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 8,
  },
  ContainerRowAdventage: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 10,
  },
  ContainerAdvantages: {
    marginTop: 15,
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    marginBottom: 20,
  },
  ContainerCircle: {
    width: 20,
    height: 20,
    backgroundColor: "#20c997",
    borderRadius: 10,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 10,
  },
  ContainerHeader: {
    width: "100%",
    alignSelf: "flex-start",
  },
  ContainerFooter: {
    width: "100%",
    alignSelf: "flex-end",
  },
  ButtonBuyNow: {
    alignContent: "center",
    backgroundColor: "#128c7e",
    borderRadius: 12,
    paddingVertical: 14,
    paddingHorizontal: 32,
    shadowColor: "#20c997",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.6,
    shadowRadius: 8,
    elevation: 4,
  },
  ContainerMostPopular: {
    backgroundColor: "#FFD700",
    borderTopLeftRadius: 12,
    borderTopRightRadius: 12,
    paddingVertical: 6,
    paddingHorizontal: 16,
    marginBottom: -10,
    zIndex: 10,
  },
  PopularText: {
    color: "#1a1a1a",
    fontWeight: "bold",
    fontSize: 14,
    textAlign: "center",
  },
});
