import { StyleSheet } from "react-native"

export const styles = StyleSheet.create({
  MainContainer: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    marginVertical: 8,
    paddingHorizontal: 8,
  },
  containerCardMethodOfPay: {
    margin: 8,
    width: 280,
    borderRadius: 24,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.25,
    shadowRadius: 16,
    elevation: 12,
    overflow: "hidden",
  },
  cardPressed: {
    shadowOpacity: 0.4,
    elevation: 16,
  },
  popularCard: {
    borderWidth: 2,
    borderColor: "#FFD700",
    shadowColor: "#FFD700",
    shadowOpacity: 0.3,
  },
  cardGradient: {
    padding: 24,
    borderRadius: 24,
    minHeight: 320,
    justifyContent: "space-between",
  },
  titleContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  crownIcon: {
    marginLeft: 8,
  },
  priceContainer: {
    flexDirection: "row",
    alignItems: "baseline",
    marginBottom: 20,
  },
  WhiteText: {
    color: "rgba(255,255,255,0.9)",
    fontSize: 14,
    lineHeight: 20,
  },
  WhiteTextBold: {
    color: "white",
    fontWeight: "800",
    fontSize: 20,
    letterSpacing: 0.5,
  },
  WhiteTextPrice: {
    color: "#20c997",
    fontWeight: "800",
    fontSize: 28,
    marginRight: 6,
    textShadowColor: "rgba(0,0,0,0.3)",
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  ContainerRowAdventage: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
    paddingLeft: 4,
  },
  ContainerAdvantages: {
    marginTop: 8,
    marginBottom: 24,
  },
  ContainerCircle: {
    width: 22,
    height: 22,
    borderRadius: 11,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
  },
  ContainerHeader: {
    flex: 1,
  },
  ContainerFooter: {
    marginTop: "auto",
  },
  ButtonBuyNow: {
    borderRadius: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
  },
  buttonPressable: {
    paddingVertical: 16,
    paddingHorizontal: 24,
    alignItems: "center",
    justifyContent: "center",
  },
  buttonText: {
    color: "white",
    fontSize: 16,
    fontWeight: "700",
    letterSpacing: 0.5,
  },
  ContainerMostPopular: {
    position: "absolute",
    top: -8,
    zIndex: 10,
    borderRadius: 20,
    overflow: "hidden",
    shadowColor: "#FFD700",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.4,
    shadowRadius: 6,
    elevation: 8,
  },
  PopularGradient: {
    paddingVertical: 8,
    paddingHorizontal: 20,
  },
  PopularText: {
    color: "#1a1a1a",
    fontWeight: "800",
    fontSize: 13,
    textAlign: "center",
    letterSpacing: 0.5,
  },
})
