import { StyleSheet } from "react-native"
import { Colors } from "@/constants/Colors"

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: "#fff",
    },
    loadingContainer: {
        flex: 1,
        justifyContent: "center",
        alignItems: "center",
    },
    loadingText: {
        marginTop: 16,
        fontSize: 16,
        color: Colors.light.tabIconDefault,
    },
    header: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        paddingHorizontal: 16,
        paddingVertical: 20,
    },
    headerTitle: {
        fontSize: 20,
        fontWeight: "bold",
        color: Colors.light.text,
    },
    addButton: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: "#f8f9fa",
        borderWidth: 2,
        borderColor: Colors.light.primary,
        justifyContent: "center",
        alignItems: "center",
    },
    menusList: {
        flex: 1,
        paddingHorizontal: 16,
    },
    menuCard: {
        backgroundColor: "#fff",
        borderRadius: 12,
        marginBottom: 16,
        shadowColor: "#000",
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.1,
        shadowRadius: 3.84,
        elevation: 5,
        overflow: "hidden",
    },
    menuImageContainer: {
        position: "relative",
    },
menuImage: {
  width: "100%",
  height: 200,
  resizeMode: "contain",
},
    menuStatusBadge: {
        position: "absolute",
        top: 12,
        right: 12,
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: "rgba(255, 255, 255, 0.9)",
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 12,
    },
    menuStatusText: {
        fontSize: 12,
        fontWeight: "bold",
        marginLeft: 4,
    },
    menuContent: {
        padding: 16,
    },
    menuTitle: {
        fontSize: 18,
        fontWeight: "bold",
        color: Colors.light.text,
        marginBottom: 4,
    },
    menuDate: {
        fontSize: 14,
        color: Colors.light.tabIconDefault,
        marginBottom: 12,
    },
    productsDetectedContainer: {
        flexDirection: "row",
        alignItems: "center",
        marginBottom: 16,
    },
    productsDetectedText: {
        fontSize: 14,
        color: Colors.light.primary,
        marginLeft: 6,
        fontWeight: "500",
    },
    menuActions: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
    },
    validateButton: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: Colors.light.primary,
        paddingHorizontal: 16,
        paddingVertical: 8,
        borderRadius: 6,
        flex: 1,
        marginRight: 12,
        justifyContent: "center",
    },
    validateButtonText: {
        color: "#fff",
        fontWeight: "bold",
        marginLeft: 6,
    },
    deleteButton: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: "#FEF2F2",
        justifyContent: "center",
        alignItems: "center",
    },
    emptyStateContainer: {
        flex: 1,
        justifyContent: "center",
        alignItems: "center",
        paddingHorizontal: 32,
    },
    emptyStateAnimation: {
        width: 200,
        height: 200,
    },
    emptyStateTitle: {
        fontSize: 20,
        fontWeight: "bold",
        color: Colors.light.text,
        textAlign: "center",
        marginBottom: 8,
    },
    emptyStateSubtitle: {
        fontSize: 16,
        color: Colors.light.tabIconDefault,
        textAlign: "center",
        marginBottom: 32,
        lineHeight: 24,
    },
    addMenuButtonsContainer: {
        flexDirection: "row",
        gap: 16,
        marginBottom: 32,
    },
    addMenuButton: {
        flexDirection: "row",
        alignItems: "center",
        paddingHorizontal: 20,
        paddingVertical: 12,
        borderRadius: 8,
        minWidth: 120,
        justifyContent: "center",
    },
    cameraButton: {
        backgroundColor: Colors.light.primary,
    },
    galleryButton: {
        backgroundColor: "#6B7280",
    },
    addMenuButtonText: {
        color: "#fff",
        fontWeight: "bold",
        marginLeft: 8,
    },
    uploadingContainer: {
        alignItems: "center",
        padding: 20,
    },
    uploadingOverlay: {
        position: "absolute",
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: "rgba(0, 0, 0, 0.4)",
        justifyContent: "center",
        alignItems: "center",
    },
    uploadingText: {
        marginTop: 12,
        fontSize: 16,
        color: 'white',
        textAlign: "center",
    },
    confirmationContainer: {
        flex: 1,
        backgroundColor: "#fff",
    },
    confirmationHeader: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        paddingHorizontal: 16,
        paddingVertical: 12,
        borderBottomWidth: 1,
        borderBottomColor: "#e5e7eb",
    },
    backButton: {
        padding: 8,
    },
    confirmationTitle: {
        fontSize: 18,
        fontWeight: "bold",
        color: Colors.light.text,
    },
    headerRight: {
        width: 32,
    },
    uploadedImageContainer: {
        margin:'auto',
        width: 250,
        aspectRatio: 4 / 3,
        borderRadius: 12,
        overflow: "hidden",
        marginVertical:12
    },
    uploadedImage: {
        width: "100%",
        height: "100%",
        resizeMode: "cover",
    },
    imageOverlay: {
        position: "absolute",
        bottom: 0,
        left: 0,
        right: 0,
        backgroundColor: "rgba(0, 0, 0, 0.7)",
        padding: 12,
    },
    detectionSummary: {
        color: "#fff",
        fontSize: 14,
        fontWeight: "bold",
    },
    menuNameContainer: {
        paddingHorizontal: 16,
        marginBottom: 16,
    },
    menuNameLabel: {
        fontSize: 16,
        fontWeight: "bold",
        color: Colors.light.text,
        marginBottom: 8,
    },
    menuNameInput: {
        borderWidth: 1,
        borderColor: "#d1d5db",
        borderRadius: 8,
        paddingHorizontal: 12,
        paddingVertical: 10,
        fontSize: 16,
        backgroundColor: "#f9fafb",
    },
    productsList: {
        flex: 1,
        paddingHorizontal: 16,
    },
    sectionTitle: {
        fontSize: 18,
        fontWeight: "bold",
        color: Colors.light.text,
        marginBottom: 16,
    },
    bulkActionsContainer: {
        paddingHorizontal: 16,
        marginBottom: 16,
    },
    bulkActions: {
        flexDirection: "row",
        gap: 12,
        marginTop: 8,
    },
    bulkActionButton: {
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 6,
        borderWidth: 1,
        borderColor: Colors.light.primary,
        backgroundColor: "transparent",
    },
    bulkActionText: {
        fontSize: 12,
        color: Colors.light.primary,
        fontWeight: "500",
    },
    bottomActions: {
        borderTopWidth: 1,
        borderTopColor: "#e5e7eb",
        backgroundColor: "#fff",
        paddingHorizontal: 16,
        paddingVertical: 12,
    },
    summaryContainer: {
        marginBottom: 12,
    },
    summaryText: {
        fontSize: 14,
        color: Colors.light.tabIconDefault,
        textAlign: "center",
    },
    actionButtons: {
        flexDirection: "row",
        gap: 12,
    },
    cancelButton: {
        flex: 1,
        paddingVertical: 12,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: "#d1d5db",
        alignItems: "center",
    },
    cancelButtonText: {
        fontSize: 16,
        fontWeight: "600",
        color: Colors.light.text,
    },
    confirmButton: {
        flex: 2,
        paddingVertical: 12,
        borderRadius: 8,
        backgroundColor: Colors.light.primary,
        alignItems: "center",
    },
    confirmButtonDisabled: {
        backgroundColor: "#9ca3af",
    },
    confirmButtonText: {
        fontSize: 16,
        fontWeight: "bold",
        color: "#fff",
    },
})
