import { StyleSheet } from "react-native"
import { Colors } from "@/constants/Colors"

const styles = StyleSheet.create({
  containerOuter: {
    marginBottom: 16,
    borderRadius: 16,
  },
  container: {
    padding: 16,
    backgroundColor: "white",
    borderRadius: 16,
    position: "relative",
    overflow: "hidden",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 5,
  },
  currentUserBadge: {
    position: "absolute",
    top: 0,
    right: 0,
    backgroundColor: Colors.light.primary,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderBottomLeftRadius: 12,
    borderTopRightRadius: 16,
    zIndex: 1,
  },
  currentUserText: {
    color: "white",
    fontSize: 12,
    fontWeight: "bold",
  },
  data: {
    width: "100%",
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    marginBottom: 20,
  },
  row: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    width: "100%",
  },
  avatarContainer: {
    marginRight: 16,
    height: 56,
    width: 56,
    borderRadius: 28,
    overflow: "hidden",
  },
  avatarGradient: {
    height: 56,
    width: 56,
    borderRadius: 28,
    alignItems: "center",
    justifyContent: "center",
  },
  avatarImage: {
    height: 56,
    width: 56,
    borderRadius: 28,
  },
  avatarText: {
    fontSize: 24,
    fontWeight: "bold",
    color: "white",
  },
  userInfo: {
    flex: 1,
  },
  buttons: {
    width: "100%",
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 12,
  },
  textName: {
    fontWeight: "bold",
    fontSize: 18,
    color: "#000035",
    marginBottom: 4,
  },
  textCorreo: {
    color: "#8e8e95",
    marginBottom: 8,
  },
  buttonEdit: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    borderColor: Colors.light.primary,
    opacity: 0.8,
    borderWidth: 1,
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  buttonDelete: {
    backgroundColor: "#DC2626",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  textEdit: {
    color: Colors.light.primary,
    fontWeight: "500",
  },
  textDelete: {
    color: "white",
    fontWeight: "500",
  },
  statusBadge: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    alignSelf: "flex-start",
  },
  statusDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    marginRight: 6,
  },
  statusText: {
    fontSize: 12,
    fontWeight: "600",
  },
  disabledDelete: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: "#bfbfbf",
  },
  noPermissionText: {
    alignSelf: "flex-end",
    color: "#8e8e95",
    fontStyle: "italic",
    fontSize: 12,
  },
})

export default styles
